# Generated by Django 4.0.4 on 2022-06-19 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('idPersona', models.AutoField(primary_key=True, serialize=False)),
                ('pasaporte', models.CharField(default='', max_length=9, null=True, unique=True)),
                ('dui', models.CharField(default='', max_length=10, null=True, unique=True)),
                ('nombre', models.CharField(default='', max_length=50)),
                ('apellido', models.CharField(default='', max_length=50)),
                ('tipoDocumento', models.IntegerField(blank=True, choices=[(1, 'DUI'), (2, 'Pasaporte')])),
                ('nacionalidad', models.IntegerField(blank=True, choices=[(1, 'Nacional'), (2, 'Extranjero')])),
                ('estado', models.IntegerField(blank=True, choices=[(1, 'Fuera del Paìs'), (2, 'En el Pais')])),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaSalida', models.DateField()),
                ('TiempoPermanencia', models.CharField(default='', max_length=10)),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flujoMigratorio.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaIngreso', models.DateField()),
                ('TiempoPermanencia', models.CharField(default='', max_length=10)),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flujoMigratorio.persona')),
            ],
        ),
    ]
