# Generated by Django 4.0.4 on 2022-06-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujoMigratorio', '0002_entrada_paisorigen_salida_paisdestino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='dui',
            field=models.CharField(blank=True, default='', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='pasaporte',
            field=models.CharField(blank=True, default='', max_length=9, null=True, unique=True),
        ),
    ]
