# Generated by Django 4.0.4 on 2022-06-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujoMigratorio', '0004_entrada_passdui'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='passDui',
        ),
        migrations.AlterField(
            model_name='entrada',
            name='TiempoPermanencia',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='salida',
            name='TiempoPermanencia',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
