# Generated by Django 4.0.4 on 2022-06-20 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flujoMigratorio', '0005_remove_entrada_passdui_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoAlerta', models.IntegerField(blank=True, choices=[(1, 'Alarma 1'), (2, 'Alarma 2')])),
                ('descripcion', models.TextField(blank=True, default='', max_length=200)),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flujoMigratorio.persona')),
            ],
        ),
    ]
